SELECT requestid,
       SALUTATION,
       _usdegreedate,
       _USSN,
       EMP_NAME,
       Last_Name,
       Gender_Text,
       _usieducation,
       _statesecondry,
       _twonsecondry,
       _usdegree,
       Aptflnum,
       town,
       [state],
       zipcode,
       _CNS,
       DSE,
       _SEVIS,
       _EADN,
       _Consulateloc,
       _ConsulateLocationfc,
       _I94ADRN,
       _I94DOI,
       _I94DOE,
       _I94DOE1,
       _streetnumber,
       _StNumber,
       _Aptflrnumber,
       _Country,
       DOBcountry,
       City_Birth,
       State_Birth,
       Country_Citizenship,
       _CWA,
       CRA_Street,
       CRA_AptSteFlr,
       CRA_state,
       CRA_city,
       CRA_zip,
       CRA_Country,
       CRA_mailing,
       StreetName,
       AptSteFlrNumber,
       _city,
       _state,
       _zip,
       _AptSteFlr,
       _citytown,
       DESIGNATION,
       _CurrentSalary,
       [Stat],
       _ZipCode,
       Date_Issue,
       Passport_No,
       DATE_OF_EXPIRY,
       Inssuncecountry_TEXT,
       _Nationality,
       _HmDepent,
       _DNo,
       _removalproce,
       _greencard,
       _PriClname,
       _StNumbername,
       _twon,
       MOBILE_NO,
       _pinCode,
       _J1EV,
       _RPAR,
       GBDAT,
       DATE_OF_JOINING_HCL,
       _I485receiptno,
       _I140Rn,
       _compname,
       _PageEntry,
       _Wpvt,
       _MJ1D,
       _usECV,
       _UsFrom,
       _ustill,
       _nonimmigrant,
       _federal,
       _SSI,
       _tanf,
       _ga,
       _snap,
       _hcvp,
       _pbra,
       _usacd,
       _ffm,
       _lpb,
       _lcapb,
       _arm,
       _cusas,
       _spouse,
       _ppp,
       _pbus,
       _ccrus,
       _nsa,
       emc,
       _idea,
       _sbb,
       _age,
       _prag,
       _datefrom,
       _dateto,
       _ARN,
       working,
       EmpLoyeeName,
       DEPENDENT_NAME,
       CM_TotalDependent,
       Employee_Code,
       SUB_BAND,
       SUB_GROUP_BAND,
       COUNTRY_OF_BIRTH,
       Maritial_Status_text,
       Company_Email_ID,
       NATIONALITY_TEXT,
       TOTAL_IT_EXP,
       _HDno,
       [Classification],
       RequestedAction,
       DateOfIntendedEmploymentToDate,
       DateOfIntendedEmploymentStartDate,
       _onsiteJobTitle,
       _ClientList,
       _ProjectList,
       _BillableCostCenter,
       COSTCENTRECODE,
       _SriClname,
       _StNumbernamescl,
       _Aptflrscl,
       _zipCodesecondry,
       _SriClnamecl2,
       _StNumbernamecl2,
       _Aptflrcl2,
       _statesecondrytwo,
       _twonsecondrytwo,
       _zipCodesecondrytwo,
       _DOLA,
       PSA_DESC,
       WORKING_ADDRESS,
       _Dsedate,
       ReceiptNumber,
       _VisaValidfrom1,
       _Visavalidtill1
INTO #temp
FROM GISSaveRequestedJson sjson WITH (NOLOCK)
CROSS APPLY OPENJSON(sjson.Responses)
WITH (
    SALUTATION NVARCHAR(MAX) '$.SALUTATION_DESC',
    _usdegreedate NVARCHAR(MAX) '$._usdegreedate',
    _USSN NVARCHAR(MAX) '$._USSN',
    EMP_NAME NVARCHAR(MAX) '$.EmpLoyeeName',
    Last_Name NVARCHAR(MAX) '$.Last_Name',
    Gender_Text NVARCHAR(MAX) '$.Gender_Text',
    _usieducation NVARCHAR(MAX) '$._usieducation',
    _statesecondry NVARCHAR(MAX) '$._statesecondry',
    _twonsecondry NVARCHAR(MAX) '$._twonsecondry',
    _usdegree NVARCHAR(MAX) '$._usdegree',
    Aptflnum NVARCHAR(MAX) '$.Aptflnum',
    town NVARCHAR(MAX) '$.town',
    [state] NVARCHAR(MAX) '$.state',
    zipcode NVARCHAR(MAX) '$.zipcode',
    _CNS NVARCHAR(MAX) '$._CNS',
    DSE NVARCHAR(MAX) '$.DSE',
    _SEVIS NVARCHAR(MAX) '$._SEVIS',
    _EADN NVARCHAR(MAX) '$._EADN',
    _Consulateloc NVARCHAR(MAX) '$._Consulateloc',
    _ConsulateLocationfc NVARCHAR(MAX) '$._ConsulateLocationfc',
    _I94ADRN NVARCHAR(MAX) '$._I94ADRN',
    _I94DOI NVARCHAR(MAX) '$._I94DOI',
    _I94DOE NVARCHAR(MAX) '$._I94DOE',
    _I94DOE1 NVARCHAR(MAX) '$.DateOfLastExpiry',
    _streetnumber NVARCHAR(MAX) '$._streetnumber',
    _StNumber NVARCHAR(MAX) '$._StNumber',
    _Aptflrnumber NVARCHAR(MAX) '$._Aptflrnumber',
    _Country NVARCHAR(MAX) '$._Country',
    DOBcountry NVARCHAR(MAX) '$.Country_Birth',
    City_Birth NVARCHAR(MAX) '$.City_Birth',
    State_Birth NVARCHAR(MAX) '$.State_Birth',
    Country_Citizenship NVARCHAR(MAX) '$.Country_Citizenship',
    _CWA NVARCHAR(MAX) '$._CWA',
    CRA_Street NVARCHAR(MAX) '$.CRA_Street',
    CRA_AptSteFlr NVARCHAR(MAX) '$.CRA_AptSteFlr',
    CRA_state NVARCHAR(MAX) '$.CRA_state',
    CRA_city NVARCHAR(MAX) '$.CRA_city',
    CRA_zip NVARCHAR(MAX) '$.CRA_zip',
    CRA_Country NVARCHAR(MAX) '$.CRA_Country',
    CRA_mailing NVARCHAR(MAX) '$.CRA_mailing',
    StreetName NVARCHAR(MAX) '$._StreetName',
    AptSteFlrNumber NVARCHAR(MAX) '$._AptSteFlrNumber',
    _city NVARCHAR(MAX) '$._city',
    _state NVARCHAR(MAX) '$._state',
    _zip NVARCHAR(MAX) '$._zip',
    _AptSteFlr NVARCHAR(MAX) '$._AptSteFlr',
    _citytown NVARCHAR(MAX) '$._citytown',
    DESIGNATION NVARCHAR(MAX) '$.DESIGNATION',
    _CurrentSalary NVARCHAR(MAX) '$._CurrentSalary',
    [Stat] NVARCHAR(MAX) '$._State',
    _ZipCode NVARCHAR(MAX) '$._ZipCode',
    Date_Issue NVARCHAR(MAX) '$.Date_Issue',
    Passport_No NVARCHAR(MAX) '$.Passport_No',
    DATE_OF_EXPIRY NVARCHAR(MAX) '$.DATE_OF_EXPIRY',
    Inssuncecountry_TEXT NVARCHAR(MAX) '$.Inssuncecountry_TEXT',
    _Nationality NVARCHAR(MAX) '$._Nationality',
    _HmDepent NVARCHAR(MAX) '$._HmDepent',
    _DNo NVARCHAR(MAX) '$._DNo',
    _removalproce NVARCHAR(MAX) '$._removalproce',
    _greencard NVARCHAR(MAX) '$._greencard',
    _PriClname NVARCHAR(MAX) '$._PriClname',
    _StNumbername NVARCHAR(MAX) '$._StNumbername',
    _twon NVARCHAR(MAX) '$._twon',
    MOBILE_NO NVARCHAR(MAX) '$.MOBILE_NO',
    _pinCode NVARCHAR(MAX) '$._zipCode',
    _J1EV NVARCHAR(MAX) '$._J1EV',
    _RPAR NVARCHAR(MAX) '$._RPAR',
    GBDAT NVARCHAR(MAX) '$.GBDAT',
    DATE_OF_JOINING_HCL NVARCHAR(MAX) '$.DATE_OF_JOINING_HCL',
    _I485receiptno NVARCHAR(MAX) '$._I485receiptno',
    _I140Rn NVARCHAR(MAX) '$._I140Rn',
    _compname NVARCHAR(MAX) '$._compname',
    _PageEntry NVARCHAR(MAX) '$._PageEntry',
    _Wpvt NVARCHAR(MAX) '$._Wpvt',
    _MJ1D NVARCHAR(MAX) '$._MJ1D',
    _usECV NVARCHAR(MAX) '$._usECV',
    _UsFrom NVARCHAR(MAX) '$._UsFrom',
    _ustill NVARCHAR(MAX) '$._ustill',
    _nonimmigrant NVARCHAR(MAX) '$._nonimmigrant',
    _federal NVARCHAR(MAX) '$._federal',
    _SSI NVARCHAR(MAX) '$._SSI',
    _tanf NVARCHAR(MAX) '$._tanf',
    _ga NVARCHAR(MAX) '$._ga',
    _snap NVARCHAR(MAX) '$._snap',
    _hcvp NVARCHAR(MAX) '$._hcvp',
    _pbra NVARCHAR(MAX) '$._pbra',
    _usacd NVARCHAR(MAX) '$._usacd',
    _ffm NVARCHAR(MAX) '$._ffm',
    _lpb NVARCHAR(MAX) '$._lpb',
    _lcapb NVARCHAR(MAX) '$._lcapb',
    _arm NVARCHAR(MAX) '$._arm',
    _cusas NVARCHAR(MAX) '$._cusas',
    _spouse NVARCHAR(MAX) '$._spouse',
    _ppp NVARCHAR(MAX) '$._ppp',
    _pbus NVARCHAR(MAX) '$._pbus',
    _ccrus NVARCHAR(MAX) '$._ccrus',
    _nsa NVARCHAR(MAX) '$._nsa',
    emc NVARCHAR(MAX) '$.emc',
    _idea NVARCHAR(MAX) '$._idea',
    _sbb NVARCHAR(MAX) '$._sbb',
    _age NVARCHAR(MAX) '$._age',
    _prag NVARCHAR(MAX) '$._prag',
    _datefrom NVARCHAR(MAX) '$._datefrom',
    _dateto NVARCHAR(MAX) '$._dateto',
    _ARN NVARCHAR(MAX) '$._ARN',
    working NVARCHAR(MAX) '$.working',
    EmpLoyeeName NVARCHAR(MAX) '$.EmpLoyeeName',
    DEPENDENT_NAME NVARCHAR(MAX) '$.DEPENDENT_NAME',
    CM_TotalDependent NVARCHAR(MAX) '$.CM_TotalDependent',
    Employee_Code NVARCHAR(MAX) '$.Employee_Code',
    SUB_BAND NVARCHAR(MAX) '$.SUB_BAND',
    SUB_GROUP_BAND NVARCHAR(MAX) '$.SUB_GROUP_BAND',
    COUNTRY_OF_BIRTH NVARCHAR(MAX) '$.COUNTRY_OF_BIRTH',
    Maritial_Status_text NVARCHAR(MAX) '$.Maritial_Status_text',
    Company_Email_ID NVARCHAR(MAX) '$.Company_Email_ID',
    NATIONALITY_TEXT NVARCHAR(MAX) '$.NATIONALITY_TEXT',
    TOTAL_IT_EXP NVARCHAR(MAX) '$.TOTAL_IT_EXP',
    _HDno NVARCHAR(MAX) '$._HDno',
    [Classification] NVARCHAR(MAX) '$.Classification',
    RequestedAction NVARCHAR(MAX) '$.RequestedAction',
    DateOfIntendedEmploymentToDate NVARCHAR(MAX) '$.DateOfIntendedEmploymentToDate',
    DateOfIntendedEmploymentStartDate NVARCHAR(MAX) '$.DateOfIntendedEmploymentStartDate',
    _onsiteJobTitle NVARCHAR(MAX) '$._onsiteJobTitle',
    _ClientList NVARCHAR(MAX) '$._ClientList',
    _ProjectList NVARCHAR(MAX) '$._ProjectList',
    _BillableCostCenter NVARCHAR(MAX) '$._BillableCostCenter',
    COSTCENTRECODE NVARCHAR(MAX) '$.COSTCENTRECODE',
    _SriClname NVARCHAR(MAX) '$._SriClname',
    _StNumbernamescl NVARCHAR(MAX) '$._StNumbernamescl',
    _Aptflrscl NVARCHAR(MAX) '$._Aptflrscl',
    _zipCodesecondry NVARCHAR(MAX) '$._zipCodesecondry',
    _SriClnamecl2 NVARCHAR(MAX) '$._SriClnamecl2',
    _StNumbernamecl2 NVARCHAR(MAX) '$._StNumbernamecl2',
    _Aptflrcl2 NVARCHAR(MAX) '$._Aptflrcl2',
    _statesecondrytwo NVARCHAR(MAX) '$._statesecondrytwo',
    _twonsecondrytwo NVARCHAR(MAX) '$._twonsecondrytwo',
    _zipCodesecondrytwo NVARCHAR(MAX) '$._zipCodesecondrytwo',
    _DOLA NVARCHAR(MAX) '$._DOLA',
    PSA_DESC NVARCHAR(MAX) '$.PSA_DESC',
    WORKING_ADDRESS NVARCHAR(MAX) '$.WORKING_ADDRESS',
    _Dsedate NVARCHAR(MAX) '$._Dsedate',
    ReceiptNumber NVARCHAR(MAX) '$."0".ReceiptNumber',
    _VisaValidfrom1 NVARCHAR(MAX) '$."0".ValidFrom',
    _Visavalidtill1 NVARCHAR(MAX) '$."0".ValidTill'
);